config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#dashboard'
  get 'admin/members'
  get 'admin/providers'
  get 'admin/assesment'

  root "admin#dashboard"
  devise_for :admins

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #enum role: %i[super_admin admin]

  enum role: [:super_admin, :admin]
  after_initialize :set_default_role, :if => :new_record?

  private

  def set_default_role
    self.role ||= :admin
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  end

  def assesment
  end

  def providers
  end

  def members
    @admins = Admin.all
  end

  def show_member
    @admin = Admin.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/assesment.html.erb
<% content_for(:sidebar) do %>
<%= render :partial => "layouts/sidebar" %>
<%end%>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1>Assesment</h1>
        </div>
      </div>
    </div>
  </div>

app/views/admin/dashboard.html.erb
<% content_for(:sidebar) do %>
<%= render :partial => "layouts/sidebar" %>
<%end%>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1>Dashboard</h1>
        </div>
      </div>
    </div>
  </div>

app/views/admin/members.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<%end%>
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div style="float:right;">
          <% if current_admin.super_admin? %>
            <%= link_to  "Invite Admin", new_admin_invitation_path, class:'button button1' %>
          <%end%>
        </div>
        <br/>
        <h4 class="text-left">Admins</h4>
        <table id="member" class="table table-light table-striped">
          <thead>
            <tr>
              <th scope="col" class="text-center">Id</th>
              <th scope="col" class="text-center">Email</th>
              <th scope="col" class="text-center">Created by invite</th>
              <th scope="col" class="text-center">Account Status</th>
            </tr>
          </thead>
          <tbody>
            <% @admins.each do |admin| %>
              <tr>
                <td class="text-center"><%= admin.id %></td>
                <td class="text-center"><%= admin.email%></td>
                <td class="text-center">
                  <% if admin.created_by_invite? == true%>
                    <span class="badge badge-success">True</span>
                  <%else%>
                    <span class="badge badge-warning">False</span>
                  <%end%>
                </td>
                <td class="text-center">
                  <% if admin.invitation_accepted? == true%>
                    <span class="badge badge-success">Approved</span>
                  <%else%>
                    <span class="badge badge-warning">Pending</span>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <script>
          $(document).ready(function () {
            var table = $('#member').DataTable( {
              responsive: true,
              lengthChange: false,
              ordering: false,
              pageLength : 7,
            } )
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/admin/providers.html.erb
<% content_for(:sidebar) do %>
<%= render :partial => "layouts/sidebar" %>
<%end%>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1>Providers</h1>
        </div>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar">
<div class="container-fluid">
  <div class="header">
    <div class="dropdown" style="float:right;">
      <button class="button button2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        System admin
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Log Out", destroy_admin_session_path, method: :delete, class:"dropdown-item"%>
        <%= link_to  "Change password", edit_admin_password_path, class:"dropdown-item"%>
      </div>
    </div>
  </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="wrapper">
  <div class="container-fluid">
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand">
          <a href="#">
            Identify U
          </a>
        </li>
        <li>
          <%= link_to  "Dashboard", admin_path%>
        </li>
        <li>
          <%= link_to  "Admins", admin_members_path %>
        </li>
        <li>
          <%= link_to  "Providers", admin_providers_path %>
        </li>
        <li>
          <a href="#">Members</a>
        </li>
        <li>
          <%= link_to  "Admins", admin_assesment_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackOffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- ✅ Load CSS file for DataTables  -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css"
      integrity="sha512-1k7mWiTNoyx2XtmI96o+hdjP8nn0f3Z2N4oF/9ZZRgijyV4omsKOXEnqL1gKQNPy2MTSP9rIEWGcH/CInulptA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body class="background">
  <% if admin_signed_in? %>
    <%= render 'layouts/header'%>
    <%end%>
    <div class="container-fluid">
      <div class="row">
        <%= yield :sidebar %>
        <%= yield %>
      </div>
    </div>
    <!-- ✅ load jQuery ✅ -->
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>

    <!-- ✅ load DataTables ✅ -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"
      integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>